"""Initial migration with questions and options

Revision ID: 640faf7d8620
Revises: 
Create Date: 2025-09-12 15:54:56.654077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640faf7d8620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('text_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_responses')
    op.drop_table('survey_responses')
    # ### end Alembic commands ###
